name: opencda
channels:
  - defaults
dependencies:
  - pip==21.1.2
  - python==3.7.10
  - pip:
    - torch==1.10.0+cu113
    - torchvision==0.11.1+cu113
    - torchaudio==0.10.0+cu113
    - matplotlib==3.4.2
    - networkx==2.5.1
    - numpy
    - pillow
    - pyparsing==2.4.7
    - six==1.16.0
    - open3d==0.10.0.0
    - opencv-python==4.5.2.52
    - pandas
    - pygame
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - seaborn
    - lxml
    - shapely==1.8.4
    - omegaconf
    - yolov5==7.0.0