site_name: OpenCDA
repo_url: https://github.com/ucla-mobility/OpenCDA.git
docs_dir: docs
theme: readthedocs
extra_css: [extra.css]

nav:
    - Home: index.md
    - Introduction: OpenCDA_introduction.md
    - Installation: OpenCDA_installation.md
    - Quick Start: OpenCDA_getstarted.md
    - Tutorials: OpenCDA_tutorial.md
    - PythonAPI: PythonAPI.md

